// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  guideSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/robodriver',
        'overview/compare',
        'overview/dataset',
        'overview/installation',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting_started/robodriver_sim',
        'getting_started/roboxstudio',
        {
          type: 'category',
          label: 'Integration',
          items: [
            'getting_started/integration/integration',
            'getting_started/integration/robot',
            'getting_started/integration/teleoperator',
            'getting_started/integration/camera',
            'getting_started/integration/policy',
          ],
        },
        'getting_started/lerobot',
      ],
    },
  ],
  
};

export default sidebars;
